import '../../models/home_training_model.dart';

List<Model> users =[
  Model(name: 'Captain Ahmed ',
    data: '08:00 AM',
    message: 'صباح الخير ياابو الكباتن',
    photos:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyBW50HXz_R2LLQhQKsdDh4SsyT7ktZCXL5A&usqp=CAU',
  ),
  Model(name: 'Captain Zizo ',
    data: '10:00 AM',
    message: 'حبيبى اخوك',
    photos:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6SjaurVHFHLWttsEZ_i6zx5SqzAy8zblclg&usqp=CAU',
  ),
  Model(name: 'Captain Hima ',
    data: '10:00 AM',
    message: 'حبيبى اخوك',
    photos:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQerGPjv9qbMQMRPLhzBOm4YeTF1yGPD8ZVMg&usqp=CAU',
  ),
  Model(name: 'Captain Mido ',
    data: '10:00 AM',
    message: 'حبيبى اخوك',
    photos:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSinsRXX4zNFzOZogyaxaa0IZjCNPH4yw-3bA&usqp=CAU',
  ),
  Model(name: 'Captain Mia ',
    data: '10:00 AM',
    message: 'انضف بنج فى الجيم',
    photos:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStvLqSH_dOow5dxDRr6dHVpz_rk4EggXYzFQ&usqp=CAU',
  ),
  Model(name: 'Captain Gigi ',
    data: '10:00 AM',
    message: 'ام قلب كبير',
    photos:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUGbL1iGhCvelWTl2qbs_B2jNc41tYOSCU4A&usqp=CAU',
  ),
  Model(name: 'Captain Soso ',
    data: '10:00 AM',
    message: 'صباح الجمال',
    photos:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSpqsJTeKD2KQjS2jCFjgAGZJvEpug3Ecm-Q&usqp=CAU',
  ),
  Model(name: 'Captain Salma ',
    data: '10:00 AM',
    message: 'ما تحن ياجن',
    photos:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStvLqSH_dOow5dxDRr6dHVpz_rk4EggXYzFQ&usqp=CAU',
  ),
  Model(name: 'Captain Marina ',
    data: '10:00 AM',
    message: 'ما تحن ياجن',
    photos:'https://thumbs.dreamstime.com/b/athletic-young-woman-beautiful-body-showing-muscles-workout-gym-athletic-young-woman-beautiful-body-showing-120985126.jpg',
  ),
  Model(name: 'Captain Salma ',
    data: '10:00 AM',
    message: 'ما تحن ياجن',
    photos:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStvLqSH_dOow5dxDRr6dHVpz_rk4EggXYzFQ&usqp=CAU',
  ),
];